### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by jblobel** [psi-4ward/psitransfer#37] opened 2017-10-13 10:08 UTC
Hi,

We are interested in hosting your service in our corporation, for internal use. But as we are french, we will translate your application.

Currently, it seems that the only way to do that is to modify the source code. That is probably what we ll do : create our own fork so we can have a french version.

Have you considered putting the vocabulary in some json files in order to be able to have multiple languages without multiple forks ?

**Comment by evg-eremin** [comment] 2018-03-30 13:43
+1
we're interested in russian

**Comment by lumbric** [comment] 2018-11-07 18:49
I think this is a duplicate of #4.

**Closed** 2018-12-14 15:06 UTC
